name: webtest

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run start -- Chrome Edge Firefox
  test-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run start -- Safari